- name: Sending an e-mail using Gmail SMTP servers
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ extra_notification_user }}"
    password: "{{ extra_notification_password }}"
    to: "{{ extra_notification_to }}"
    subject: "[Tower Notification] Volterra lab - unlimited deployment duration"
    body: "User {{ extra_owner_email }} deployed an AWS VPC site, named cloudbuilder-{{ extra_volterra_site_id }}, with no duration limit set"
  delegate_to: localhost
  when: extra_duration == 0

- name: Wait until automatic deletion
  pause:
    minutes: "{{ (extra_duration*60*24)|int|abs }}"
  failed_when: extra_duration == 0




