- name: "GET VM cloudbuilder-{{ extra_volterra_site_id }}-arcadia"
  community.aws.ec2_instance_info:
    region: "{{ extra_aws_region }}"
    filters:
      instance-state-name: running
      "tag:Name": "cloudbuilder-{{ extra_volterra_site_id }}-arcadia"
      "tag:project": cloudbuilder
      "tag:ves.io/site_name": "cloudbuilder-{{ extra_volterra_site_id }}"
  register: var_vm

- name: "DELETE VM {{ var_vm.instances.0.instance_id }}"
  amazon.aws.ec2:
    state: absent
    instance_ids: ["{{ var_vm.instances.0.instance_id }}"]
    region: "{{ extra_aws_region }}"
    wait: yes
    wait_timeout: 300

